FROM mysql


ENV MYSQL_ROOT_PASSWORD=toor
ENV MYSQL_DATABASE=uniwar
ENV MYSQL_USER=alberto_giuseppe
ENV MYSQL_PASSWORD=progetto


COPY ./pythonServer/Db/init.sql /docker-entrypoint-initdb.d/


VOLUME /var/lib/mysql

