# -*- coding: utf-8 -*-
# Generated by the protocol buffer compiler.  DO NOT EDIT!
# NO CHECKED-IN PROTOBUF GENCODE
# source: statistics.proto
# Protobuf Python Version: 5.28.1
"""Generated protocol buffer code."""
from google.protobuf import descriptor as _descriptor
from google.protobuf import descriptor_pool as _descriptor_pool
from google.protobuf import runtime_version as _runtime_version
from google.protobuf import symbol_database as _symbol_database
from google.protobuf.internal import builder as _builder
_runtime_version.ValidateProtobufRuntimeVersion(
    _runtime_version.Domain.PUBLIC,
    5,
    28,
    1,
    '',
    'statistics.proto'
)
# @@protoc_insertion_point(imports)

_sym_db = _symbol_database.Default()




DESCRIPTOR = _descriptor_pool.Default().AddSerializedFile(b'\n\x10statistics.proto\x12\nstatistics\"\xfd\x01\n\x14StatisticsCollection\x12\x11\n\tplayer_id\x18\x01 \x01(\t\x12\x10\n\x08round_id\x18\x02 \x01(\x05\x12\x11\n\tuser_turn\x18\x03 \x01(\x08\x12\x18\n\x10lost_territories\x18\x04 \x03(\t\x12W\n\x14\x61ttacked_territories\x18\x05 \x03(\x0b\x32\x39.statistics.StatisticsCollection.AttackedTerritoriesEntry\x1a:\n\x18\x41ttackedTerritoriesEntry\x12\x0b\n\x03key\x18\x01 \x01(\t\x12\r\n\x05value\x18\x02 \x01(\x05:\x02\x38\x01\"8\n\x11SignInCredentials\x12\x11\n\tplayer_id\x18\x01 \x01(\t\x12\x10\n\x08password\x18\x02 \x01(\t\"8\n\x11SignUpCredentials\x12\x11\n\tplayer_id\x18\x01 \x01(\t\x12\x10\n\x08password\x18\x02 \x01(\t\"+\n\x08Response\x12\x0f\n\x07message\x18\x01 \x01(\t\x12\x0e\n\x06status\x18\x02 \x01(\x08\x32\xdb\x01\n\x11StatisticsService\x12H\n\x0eSendStatistics\x12 .statistics.StatisticsCollection\x1a\x14.statistics.Response\x12=\n\x06SignIn\x12\x1d.statistics.SignInCredentials\x1a\x14.statistics.Response\x12=\n\x06SignUp\x12\x1d.statistics.SignUpCredentials\x1a\x14.statistics.Responseb\x06proto3')

_globals = globals()
_builder.BuildMessageAndEnumDescriptors(DESCRIPTOR, _globals)
_builder.BuildTopDescriptorsAndMessages(DESCRIPTOR, 'statistics_pb2', _globals)
if not _descriptor._USE_C_DESCRIPTORS:
  DESCRIPTOR._loaded_options = None
  _globals['_STATISTICSCOLLECTION_ATTACKEDTERRITORIESENTRY']._loaded_options = None
  _globals['_STATISTICSCOLLECTION_ATTACKEDTERRITORIESENTRY']._serialized_options = b'8\001'
  _globals['_STATISTICSCOLLECTION']._serialized_start=33
  _globals['_STATISTICSCOLLECTION']._serialized_end=286
  _globals['_STATISTICSCOLLECTION_ATTACKEDTERRITORIESENTRY']._serialized_start=228
  _globals['_STATISTICSCOLLECTION_ATTACKEDTERRITORIESENTRY']._serialized_end=286
  _globals['_SIGNINCREDENTIALS']._serialized_start=288
  _globals['_SIGNINCREDENTIALS']._serialized_end=344
  _globals['_SIGNUPCREDENTIALS']._serialized_start=346
  _globals['_SIGNUPCREDENTIALS']._serialized_end=402
  _globals['_RESPONSE']._serialized_start=404
  _globals['_RESPONSE']._serialized_end=447
  _globals['_STATISTICSSERVICE']._serialized_start=450
  _globals['_STATISTICSSERVICE']._serialized_end=669
# @@protoc_insertion_point(module_scope)
